language: c

sudo: required

install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - dkp-pacman --noconfirm -Sy
  - dkp-pacman --noconfirm -S switch-dev
  - dkp-pacman --noconfirm -S devkitARM

script:
  - cd fusee
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=/opt/devkitpro/devkitARM
  - make
